---
- name: Execute bash script
  hosts: all
  become: true
  tasks:
    - name: Transfer Configuration File

      copy: src=/home/ubuntu/ansible/security_agent_config.yaml dest=/tmp/  mode=0777

    - name: Transfer Installer File

      copy: src=/home/ubuntu/ansible/security_agent_installer_linux_amd64_v1.0.0.sh dest=/tmp/ mode=0777

    - name: Run script
      shell: /tmp/security_agent_installer_linux_amd64_v1.0.0.sh --config /tmp/security_agent_config.yaml --token CSG_$h4p3#7e
      register: script_output
    - name: Write output to local text file
      local_action:
        module: copy
        content: "{{ script_output.stdout }}"
        dest: /home/ubuntu/output.txt
~                                           